### ISSUE TITLE
Where to get started?

### ISSUE THREAD

**Issue by AwokeinanEnigma** [Titanfall-3/Titanfall-3#8]
Hey, I saw this project and was wondering how I could help. I saw that in issue #7 there was mention of a trello project. I'd really like to help out!

**Comment by Harald234** [comment]
Hello and thanks for wanting to help. What are you experienced in, programming, 3d modeling or something else?

**Comment by AwokeinanEnigma** [comment]
I'm primarily experienced in programming and have worked with Unity before

**Comment by Harald234** [comment]
Ok that's good, I am not at home right now but I will get back to you later when I am.

**Comment by AwokeinanEnigma** [comment]
Alright, thanks!

**Comment by Harald234** [comment]
Hello again, can I add you on discord?

**Comment by AwokeinanEnigma** [comment]
Sure! My discord is Enigma#6973
